sudo: required
language: generic

services:
  - docker

install:
  - sudo apt-get install build-essential packaging-dev devscripts equivs --assume-yes

script:
  - make -f debian/rules get-orig-source
  - mk-build-deps -i -r
  - dpkg-buildpackage -us -uc

if:
  tag IS blank
